-- Manual one-time PostgreSQL migration file.
-- Do not run this automatically during application startup.
--
-- Earlier versions of this file used DROP COLUMN + ADD COLUMN statements for
-- text fields such as:
--   companies.description
--   notices.message
--   preparation_resources.description
-- That behavior erased persisted data whenever the app restarted.
--
-- If a schema repair is ever needed again, run a targeted manual migration in
-- Supabase/PostgreSQL that preserves existing data instead of dropping columns.
