spring.application.name=placementportal

server.port=8080

# ==========================

# Supabase PostgreSQL

# ==========================

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.vzedlfwakxwhfaiqcoyi
spring.datasource.password=Nandu@Minnu
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================

# JPA / Hibernate

# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

# ==========================

# Cloudinary

# ==========================

cloudinary.cloud-name=df9yv0c8o
cloudinary.api-key=642244593877457
cloudinary.api-secret=AmOhUX1AHLp3uY4WE0dvWiPGh2o
